### PR TITLE
pass on the statusCode if one exists

### LINKED ISSUE #16337: Non-descriptive error message when logging in with incorrect username and/or password
### Expected behavior

I would expect to display a meaningful error message on the login screen when the user entered the incorrect username and/or password.

### Actual behavior

The error message shown on the screen is "The Operation couldn't be completed. (WordPressKit.WordPressOrgXMLRPCApiError Code 0.)

IMG_32B29730A99C-1

### Steps to reproduce the behavior

1. Select "Enter your existing site address" on the app's login screen
2. Enter a self-hosted WordPress site address
3. On the next screen, enter an incorrect username and/or password

### PR DESCRIPTION
**Pull request by enejb**
### Description

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/16337

This Pr makes sure that we pass on the statusCode to the error object. 
This helps code down the line know what the response code is and act accordingly. 

Before:

After:

### Testing Details
Apply this patch and build the WordPress App. 

Try to add a new .org site.  
Type in the wrong username and password. Notice that the error makes sense.

ℹ Please replace this with a clear and concise description of the steps required to validate this pull request.

- [x] Please check here if your pull request includes additional test coverage.

### CODE REVIEW

File: WordPressKit/WordPressOrgXMLRPCApi.swift [hunk 1]
```diff
@@ -300,12 +300,14 @@ open class WordPressOrgXMLRPCApi: NSObject {
     @objc public static let WordPressOrgXMLRPCApiErrorKeyStatusCode: NSError.UserInfoKey = "WordPressOrgXMLRPCApiErrorKeyStatusCode"
 
     private func convertError(_ error: NSError, data: Data?, statusCode: Int? = nil) -> NSError {
+        let responseCode = ( (statusCode != nil) ? statusCode! : error.code );
```
Comment (enejb) [inline WordPressKit/WordPressOrgXMLRPCApi.swift]:
```suggestion
        let responseCode = ( (statusCode != nil) ? statusCode! : error.code )
```

File: WordPressKit/WordPressOrgXMLRPCApi.swift [hunk 2]
```diff
@@ -300,12 +300,14 @@ open class WordPressOrgXMLRPCApi: NSObject {
...
+
```
Comment (enejb) [inline WordPressKit/WordPressOrgXMLRPCApi.swift]:
```suggestion

```
fix trailing whitespace

File: WordPressKit/WordPressOrgXMLRPCApi.swift [hunk 3]
```diff
@@ -300,12 +300,13 @@ open class WordPressOrgXMLRPCApi: NSObject {
     @objc public static let WordPressOrgXMLRPCApiErrorKeyStatusCode: NSError.UserInfoKey = "WordPressOrgXMLRPCApiErrorKeyStatusCode"
 
     private func convertError(_ error: NSError, data: Data?, statusCode: Int? = nil) -> NSError {
+        let responseCode = ( (statusCode != nil) ? statusCode! : error.code )
```
Comment (frosty) [inline WordPressKit/WordPressOrgXMLRPCApi.swift]: Here you can just do `let responseCode = statusCode ?? error.code`

**Review by frosty — COMMENTED** [review]
Thanks for tackling this! The approach seems like it works, I'm just slightly concerned whether any of our existing code will be relying on the error code that we currently pass out. As we're already including the status code in the `userInfo` dict, I wonder if we should instead be checking this in the place where display the code. For example, the code in `displayRemoteError(_:)` of `LoginUsernamePasswordViewController` in WordPressAuthenticator might become something like this:

```
let err = error as NSError
        let statusCode = err.userInfo[WordPressOrgXMLRPCApi.WordPressOrgXMLRPCApiErrorKeyStatusCode as String] as? Int
        if err.code == 403 || statusCode == 403 {
            displayError(message: NSLocalizedString("It looks like this username/password isn't associated with this site."...
```

But I'd be very interested to get @jleandroperez's thoughts on this!

**Comment by enejb** [comment]
Thanks for the suggestion @frosty! 

I created a new PR. https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/593 works the same as this but doesn't overwrite the error.code. 

I did notice that the error code of 403 is expected in quite a few different places. so I think this Approach here might still make sense since it might fix things in multiple places? Should we just limit it to the 403 error code?

**Comment by frosty** [comment]
Interesting, do you think there are other places we're probably not handling it correctly already?  I guess if that's the case, limiting it just to 403 for now might be a safer option 🤔 I've asked Jorge on the other PR which approach he'd go for.

**Review by jleandroperez — APPROVED** [review]
:shipit:
