### PR TITLE
Fix a regression in plan flag logic

### LINKED ISSUE #579: Incorrect logic for querying if blog's plan is free
### Expected behavior

`RemoteBlog.hasPaidPlan` should return `true` on WP.com sites that have a paid plan, `false` otherwise.

### Actual behavior

The logic of `RemoteBlog.hasPaidPlan` is reversed. It returns `true` on WP.com sites that have a free plan, otherwise `true`.

### Steps to reproduce the behavior

I noticed this when calling `hasPaidPlans` in https://github.com/wordpress-mobile/WordPress-iOS/pull/20163. It unexpectedly returned `false` on a site that has a paid plan.

##### WordPressKit Environment
 - WordPressKit Version `6.1.0-beta`
 - OS: iOS 16.2
 - Device: iPhone 14 Pro Max
 - Xcode Version: Xcode 14.2

##### Additional Context

In https://github.com/wordpress-mobile/WordPressKit-iOS/pull/558, it appears that the refactor inadvertently flipped the logic on the `hasPaidPlan` bool.

### PR DESCRIPTION
**Pull request by guarani**
### Description

Fixes https://github.com/wordpress-mobile/WordPressKit-iOS/issues/579

### Testing Details

Testing instructions can be found in https://github.com/wordpress-mobile/WordPress-iOS/pull/20163.

---

- [ ] Please check here if your pull request includes additional test coverage.
- [x] I have considered updating the `version` in the `.podspec` file.
- [x] I have considered if this change warrants release notes and have added them to the appropriate section in the `CHANGELOG.md` if necessary.

### CODE REVIEW

File: WordPressKit/RemoteBlog.swift [hunk 1]
```diff
@@ -72,7 +72,7 @@ import NSObject_SafeExpectations
         self.options = RemoteBlogOptionsHelper.mapOptions(fromResponse: json)
         self.planID = json.number(forKeyPath: "plan.product_id")
         self.planTitle = json.string(forKeyPath: "plan.product_name_short")
-        self.hasPaidPlan = json.number(forKeyPath: "plan.is_free")?.boolValue ?? false
+        self.hasPaidPlan = !(json.number(forKeyPath: "plan.is_free")?.boolValue ?? false)
```
Comment (twstokes) [inline WordPressKit/RemoteBlog.swift]: 👋 Hey @guarani, I wanted to run a thought by you on this change:

I understand that this effectively reverses the value for the `plan.is_free` boolean so that it resolves the logic issue defined in the[ parent issue](https://github.com/wordpress-mobile/WordPressKit-iOS/issues/579), e.g. it's not a paid plan if the plan is free.

Is there any concern here about the _default_ value of `false` also being reversed? Before, if a `nil` value was found `hasPaidPlan` would default to `false`, but we're now defaulting to `true`.

Comment (guarani) [reply WordPressKit/RemoteBlog.swift]: Good call! I think updating the default value to `true` is the right move.

**Review by twstokes — APPROVED** [review]
LGTM @guarani! [Tests passed for me in the WPiOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/20163). 🚀

**Comment by guarani** [comment]
> LGTM @guarani! [Tests passed for me in the WPiOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/20163). 🚀

Thank you, kind sir! 🙇
