### PR TITLE
Fix crash on unexpected plugin slugs

### LINKED ISSUE #22891: [PluginDirectoryServiceRemote] NSInvalidArgumentException: *** +[NSURLComponents setPercentEncodedPath:]: invalid characters in percentEncodedPath
WordPress Issue: [WORDPRESS-IOS-4867](https://a8c.sentry.io/issues/5081512072/?referrer=github_integration)
Jetpack Issue: [JETPACK-IOS-19QJ](https://a8c.sentry.io/issues/5079722300/?referrer=github_integration)

```
NSInvalidArgumentException: *** +[NSURLComponents setPercentEncodedPath:]: invalid characters in percentEncodedPath
  File "HTTPRequestBuilder.swift", line 151, in HTTPRequestBuilder.build
  File "PluginDirectoryServiceRemote.swift", line 63, in PluginDirectoryGetInformationEndpoint.buildRequest
  File "PluginDirectoryServiceRemote.swift", line 141, in PluginDirectoryServiceRemote.getPluginInformation
  File "<compiler-generated>", in PluginStore.fetchPluginDirectoryEntry
  File "PluginStore.swift", line 697, in PluginStore.fetchPluginDirectoryEntry
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by crazytonyli**
### Description

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/22891.

The crash happens when a WordPress plugin slug contains characters that are not in percentage encoding characters set, like `%` or non ascii.

I couldn't find such plugin in [the plugin directory](https://wordpress.org/plugins) though. Also the guidelines ([here](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#what-will-my-plugin-permalink-slug-be) and [here](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#are-there-things-i-cant-do-in-a-plugin-name)) seem to indicate slug is url safe. But maybe there still could be unconventional plugin slugs in the real world...

### Testing Details

See the added unit test.

---

- [ ] Please check here if your pull request includes additional test coverage.
- [ ] I have considered if this change warrants release notes and have added them to the appropriate section in the `CHANGELOG.md` if necessary.

### CODE REVIEW

File: WordPressKitTests/PluginDirectoryTests.swift [hunk 1]
```diff
@@ -343,4 +343,16 @@ class PluginDirectoryTests: XCTestCase {
...
+        let data = try MockPluginDirectoryProvider.getPluginDirectoryMockData(with: "plugin-directory-rename-xml-rpc", sender: type(of: self))
+        stub(condition: isHost("api.wordpress.org")) { _ in
+            HTTPStubsResponse(data: data, statusCode: 200, headers: ["Content-Type": "application/json"])
+        }
+
+        let _ = try await PluginDirectoryServiceRemote().getPluginInformation(slug: "%-is-not-allowed")
+        let _ = try await PluginDirectoryServiceRemote().getPluginInformation(slug: "中文")
+
+        // No assertion needed.
+    }
```
Comment (mokagio) [inline WordPressKitTests/PluginDirectoryTests.swift]: A suggestion for your consideration.

```suggestion
        await XCTAssertNoThrow(try await PluginDirectoryServiceRemote().getPluginInformation(slug: "%-is-not-allowed"))
        await XCTAssertNoThrow(try await PluginDirectoryServiceRemote().getPluginInformation(slug: "中文"))
    }
}

func XCTAssertNoThrow<T>(
    _ expression: @autoclosure () async throws -> T,
    _ message: @autoclosure () -> String = "",
    file: StaticString = #filePath,
    line: UInt = #line
) async {
    let error: Error?
    do {
        _ = try await expression()
        error = nil
    } catch let caughtError {
        error = caughtError
    }

    XCTAssertNil(
        error,
        message().isEmpty ? "Expected to not throw, threw \(String(describing: error))" : message(),
        file: file,
        line: line
    )
}
```

The motivation for this is that a test with no assertion looks odd to me. But, having said that, XCTest will fail a test `test name() throws` that threw an error, so it might be much of a muchness...

image

**Review by mokagio — APPROVED** [review]

**Comment by mokagio** [comment]
@crazytonyli thank you for reviewing #764. It auto-merged and created conflicts with this branch, since I already had a copy checked out for the suggestion I left, I took the liberty of merging `trunk` into this to address the conflicts. My Git was able to auto-resolve them, which I'm not surprised given they were merely renames.

**Comment by mokagio** [comment]
Also, @crazytonyli, should I ship a new version of the library, so we can point WordPress to it instead than a commit? 

Again, given I made changes to the lib, including breaking changes, I'd be happy to wrangle.

File: WordPressKitTests/PluginDirectoryTests.swift (hunk 1 above)
Comment (crazytonyli) [reply WordPressKitTests/PluginDirectoryTests.swift]: > XCTest will fail a test test name() throws that threw an error, so it might be much of a muchness...

That's my thinking too. XCTest kind of makes the "no throw" assertion for us.

**Comment by crazytonyli** [comment]
> Again, given I made changes to the lib, including breaking changes, I'd be happy to wrangle.

@mokagio That'd be nice. Thanks for that!
